name: Manual Trigger
env:
      SEND_ID: ${{ secrets.SEND_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Running Scripts
        run: |
          pip install -r requirements.txt
          python script.py
